name = "discord-bots"
main = "src/worker.js"
compatibility_date = "2024-09-23"

# [vars] には機密でない設定のみ記述する
# INTRO_CHANNEL_ID は機密情報のため wrangler secret put で設定する

[[kv_namespaces]]
binding = "SESSION_KV"
id = "54654535cc2140d0b9022e4be3cf2b31"

[[kv_namespaces]]
binding = "MATCHUP_KV"
id = "923444696dc4472fb016330b9f82d439"
